### ISSUE TITLE
Browser URL limitation?

### ISSUE THREAD

**Issue by michaelherger** [typpo/quickchart#102]
This probably is more of a support question than an issue. But are there known limitations with quickchart failing to render in browsers, probably due to URL length limitation in the browsers? I'm trying to render some charts which would fail if rendered in the browser directly. But if I have my application download the image from quickchart, then send that resulting image data to the browser, I'm fine.

I looked at some of the Docker image's output and found messages like this:

```
{
    "name": "quickchart",
    "hostname": "ianw-quickchart1",
    "pid": 1,
    "level": 50,
    "msg": "Input Error vm.js:1
(function (exports, require, module, __filename, __dirname) { module.exports = {'type':'line','data':{'labels':['2021-7-8 20:53:24','2021-7-8 21:03:40','2021-7-8 21:14:01','2021-7-8 21:24:22','2021-7-8 21:34:43','2021-7-8 21:45:05','2021-7-8 21:55:25','2021-7-8 22:05:46','2021-7-8 22:16:08','2021-7-8 22:21:43','2021-7-8 22:27:19','2021-7-8 22:32:56','2021-7-8 22:41:23','2021-7-8 22:51:16','2021-7-8 22:57:49','2021-7-8 23:03:25','2021-7-8 23:09:01','2021-7-8 23:18:26','2021-7-8 23:28:48','2021-7-8 23:39:07','2021-7-8 23:49:29','2021-7-8 23:55:05','2021-7-9 0:01:10','2021-7-9 0:08:42','2021-7-9 0:14:17','2021-7-9 0:22:46','2021-7-9 0:28:49','2021-7-9 0:37:45','2021-7-9 0:48:07','2021-7-9 0:58:28','2021-7-9 1:08:50','2021-7-9 1:14:54','2021-7-9 1:25:15','2021-7-9 1:35:36','2021-7-9 1:45:29','2021-7-9 1:51:34','2021-7-9 2:01:57','2021-7-9 2:12:17','2021-7-9 2:22:38','2021-7-9 2:28:43','2021-7-9 2:39:05','2021-7-9 2:49:26','2021-7-9 2:58:50','2021-7-9 3:04:29','2021-7-9 3:14:48','2021-7-9 3:25:12','2021-

SyntaxError: Invalid or unexpected token
 at new Script (vm.js:83:7)
 at NodeVM.run (/quickchart/node_modules/vm2/lib/main.js:1108:13)
 at renderChartJs (/quickchart/lib/charts.js:130:18)
 at doChartjsRender (/quickchart/index.js:174:3)
 at renderChartToImage (/quickchart/index.js:133:3)
 at app.get (/quickchart/index.js:307:5)
 at Layer.handle [as handle_request] (/quickchart/node_modules/express/lib/router/layer.js:95:5)
 at next (/quickchart/node_modules/express/lib/router/route.js:137:13)
 at Route.dispatch (/quickchart/node_modules/express/lib/router/route.js:112:3)
 at Layer.handle [as handle_request] (/quickchart/node_modules/express/lib/router/layer.js:95:5) {'type':'line','data':{'labels':['2021-7-8 20:53:24','2021-7-8 21:03:40','2021-7-8 21:14:01','2021-7-8 21:24:22','2021-7-8 21:34:43','2021-7-8 21:45:05','2021-7-8 21:55:25','2021-7-8 22:05:46','2021-7-8 22:16:08','2021-7-8 22:21:43','2021-7-8 22:27:19','2021-7-8 22:32:56','2021-7-8 22:41:23','2021-7-8 22:51:16','2021-7-8 22:57:49','2021-7-8 23:03:25','2021-7-8 23:09:01','2021-7-8 23:18:26','2021-7-8 23:28:48','2021-7-8 23:39:07','2021-7-8 23:49:29','2021-7-8 23:55:05','2021-7-9 0:01:10','2021-7-9 0:08:42','2021-7-9 0:14:17','2021-7-9 0:22:46','2021-7-9 0:28:49','2021-7-9 0:37:45','2021-7-9 0:48:07','2021-7-9 0:58:28','2021-7-9 1:08:50','2021-7-9 1:14:54','2021-7-9 1:25:15','2021-7-9 1:35:36','2021-7-9 1:45:29','2021-7-9 1:51:34','2021-7-9 2:01:57','2021-7-9 2:12:17','2021-7-9 2:22:38','2021-7-9 2:28:43','2021-7-9 2:39:05','2021-7-9 2:49:26','2021-7-9 2:58:50','2021-7-9 3:04:29','2021-7-9 3:14:48','2021-7-9 3:25:12','2021-7-9 3:35:31','2021-7-9 3:45:22','2021-7-9 3:51:27','2021-7-9 4:01:48','2021-7-9 4:12:08','2021-7-9 4:17:45','2021-7-9 4:28:05','2021-7-9 4:38:27','2021-7-9 4:44:59','2021-7-9 4:55:21','2021-7-9 5:05:17','2021-7-9 5:11:22','2021-7-9 5:21:43','2021-7-9 5:31:35','2021-7-9 5:37:40','2021-7-9 5:48:01','2021-7-9 5:54:05','2021-7-9 5:59:42','2021-7-9 6:05:18','2021-7-9 6:10:54','2021-7-9 6:16:31','2021-7-9 6:22:07','2021-7-9 6:27:43','2021-7-9 6:33:49','2021-7-9 6:41:19','2021-7-9 6:47:23','2021-7-9 6:57:47','2021-7-9 7:03:49','2021-7-9 7:09:24','2021-7-9 7:15:01','2021-7-9 7:20:37','2021-7-9 7:26:14','2021-7-9 7:36:34','2021-7-9 7:42:39','2021-7-9 7:48:17','2021-7-9 7:53:54','2021-7-9 7:59:28','2021-7-9 8:05:35','2021-7-9 8:11:38','2021-7-9 8:21:59','2021-7-9 8:28:04','2021-7-9 8:34:09','2021-7-9 8:44:30','2021-7-9 8:50:35','2021-7-9 9:00:56','2021-7-9 9:11:17','2021-7-9 9:17:22','2021-7-9 9:27:42','2021-7-9 9:33:46','2021-7-9 9:39:51','2021-7-9 9:47:21','2021-7-9 9:52:57','2021-7-9 9:59:02','2021-7-9 10:06:32','2021-7-9 10:13:07','2021-7-9 10:23:28','2021-7-9 10:29:03','2021-7-9 10:35:09','2021-7-9 10:45:29','2021-7-9 10:51:05','2021-7-9 10:56:42','2021-7-9 11:02:18','2021-7-9 11:07:54','2021-7-9 11:15:53','2021-7-9 11:24:20','2021-7-9 11:30:25','2021-7-9 11:36:30','2021-7-9 11:42:34','2021-7-9 11:48:11','2021-7-9 11:53:47','2021-7-9 11:59:23','2021-7-9 12:05:00','2021-7-9 12:15:20','2021-7-9 12:21:28','2021-7-9 12:31:45','2021-7-9 12:37:25','2021-7-9 12:43:29','2021-7-9 12:50:31','2021-7-9 12:56:32','2021-7-9 13:06:56','2021-7-9 13:12:30','2021-7-9 13:18:05','2021-7-9 13:28:25','2021-7-9 13:38:45','2021-7-9 13:49:09','2021-7-9 13:59:01','2021-7-9 14:05:04','2021-7-9 14:10:43','2021-7-9 14:16:47','2021-7-9 14:24:18','2021-7-9 14:30:20','2021-7-9 14:37:49','2021-7-9 14:46:16','2021-7-9 14:53:46','2021-7-9 14:59:51','2021-7-9 15:05:27','2021-7-9 15:11:04','2021-7-9 15:16:40','2021-7-9 15:22:45','2021-7-9 15:33:05','2021-7-9 15:38:42','2021-7-9 15:44:46','2021-7-9 15:50:51','2021-7-9 15:57:56','2021-7-9 16:05:26','2021-7-9 16:13:51','2021-7-9 16:19:27','2021-7-9 16:25:03','2021-7-9 16:35:25','2021-7-9 16:41:30','2021",
    "time": "2021-07-10T19:31:06.889Z",
    "v": 0
}
```

I don't know whether this is the logger limiting the reported data size, or whether this really is the data quickchart is seeing. But clearly the data is incomplete.

**Comment by typpo** [comment]
Are you able to share a gist or file of your chart input?  It would be easier to troubleshoot that way.  It's possible there's some browser limitation but maybe there's something else going on.

**Comment by michaelherger** [comment]
I think there have been a few different issues with my setup. One being nginx not handling such long URLs correctly. I haven't found the solution for this yet, but then remembered why I didn't do it to start with: I don't want to expose the full Quickchart host. Therefore I'm proxying the one chart in my application.

The other issue was some incorrect URL encoding of % and ° signs. Most likely these were what caused the above error. So thanks for asking me to dig deeper.

**Comment by typpo** [comment]
Ah I see.  You'll have to set the following nginx configs to accommodate large URLs (adjust according to max URL length):
```
client_header_buffer_size 64k;
large_client_header_buffers 4 64k;
```
Let me know if you run into any other issues!
